### ISSUE TITLE
Config file support

### ISSUE THREAD

**Issue by nicmr** [Altemista/altemista-billing#31]
Everything that can currently be configured by flags, should also be possible to read from a config file
Yaml seems like an appropriate format for this task.

- [ ] ~Add support for specifying subcommands in the config file~
- [x] Fix bucket flag being required by cobra even when it is supplied by the config file.(#40)
- [x] add flag that passes path to a config file

**Comment by nicmr** [comment]
some ideas:

### Style A
```yaml
apiVersion: 1.0
month: current
targetapi: aws
```
and
```yaml
apiVersion: 1.0
serve: true
port: 8080
```
### Style B:
```yaml
apiVersion: 1.0
query: { month: current, targetapi: aws }
```
and
```yaml
apiVersion: 1.0
serve: { port: 8080 }
```
